apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ocp-gitops-namespaces
  namespace: openshift-gitops
spec:
  destination:
    namespace: ocp-gitops-namespaces
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: app
    repoURL: https://github.com/briantward/ocp-gitops-namespaces.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
